#ifndef __TECHNIQUE_H__
#define __TECHNIQUE_H__

#include "species.h"


enum {
	CATEGORY_STATUS,
	CATEGORY_PHYSICAL,
	CATEGORY_MAGIC
};

enum {
	TARGET_USER,
	TARGET_FOE_SINGLE,
	TARGET_FOES,
	TARGET_ALLY_SINGLE,
	TARGET_ALLIES,
	TARGET_FOES_AND_ALLIES,
	TARGET_FIELD,
	TARGET_ALLY_SIDE,
	TARGET_OPP_SIDE
};

typedef struct technique_s {
	u16 id;
	u8 type;
	u8 category;

	u8 power;
	u8 nrgRequired;
	s8 nrgCost;
	u8 target;

	s8 priority;
	u8 animFlags;
	u16 effectExtra;

	u16 effect;
	u8 effectChance;
	u8 effectArgs;

	u32 flags;

} TechniqueStats;

typedef struct {
	u16 technique : 9;
	u16 level : 7;
} LevelTech;

enum {
	TECHNIQUE_NONE,
	TECHNIQUE_SMACK,
	TECHNIQUE_POUND,
	TECHNIQUE_BITE,
	TECHNIQUE_GROWL,
	TECHNIQUE_WAG,
	TECHNIQUE_FLAME_BAR,
	TECHNIQUE_TIDAL_CRASH,
	TECHNIQUE_LEAF_FLURRY,
	TECHNIQUE_HEADBUTT,
	TECHNIQUE_FLURRY,
	TECHNIQUE_PURSUIT,
	TECHNIQUE_FAKEOUT,
	TECHNIQUE_FIRSTIMPRESSION,
	TECHNIQUE_SPARK,
	TECHNIQUE_GUST,
	TECHNIQUE_BUBBLE,
	TECHNIQUE_LEAFAGE,
	TECHNIQUE_SHOCK,
	TECHNIQUE_EMBER,

	TECHNIQUE_MAX
};

#define TECHFLAG_PROJECTILE		0x01
#define TECHFLAG_MAKES_CONTACT	0x02
#define TECHFLAG_NON_COPYABLE	0x04
#define	TECHFLAG_PROTECTABLE	0x08
#define TECHFLAG_HICRIT			0x10
#define TECHFLAG_ALWAYSCRIT		0x20
#define TECHFLAG_PUNCH			0x100
#define TECHFLAG_BALLISTIC		0x200
#define TECHFLAG_BITE			0x400
#define TECHFLAG_SOUND			0x800
#define TECHFLAG_DANCE			0x1000
#define TECHFLAG_KICK			0x2000

enum {
	TECHEFFECT_NONE,
	TECHEFFECT_HIT,
	TECHEFFECT_HIT_STATUS_CHANCE,
	TECHEFFECT_HIT_INFLICT_STATUS,
	TECHEFFECT_INFLICT_MAJOR_STATUS,
	TECHEFFECT_HIT_DRAIN,
	TECHEFFECT_HIT_RECOIL,
	TECHEFFECT_CLEAR_TRAPS,
	TECHEFFECT_SET_HAZARDS,
	TECHEFFECT_RAISE_OWN_STATS,
	TECHEFFECT_HIT_RAISE_OWN_STATS,
	TECHEFFECT_LOWER_TARGET_STATS,
	TECHEFFECT_HIT_LOWER_TARGET_STATS,
	TECHEFFECT_HIT_LOWER_OWN_STATS,
	TECHEFFECT_PRESWITCHIN,
	TECHEFFECT_DOUBLE_DAMAGE_POSTSWITCHIN,
	TECHEFFECT_PREEMPT,
	TECHEFFECT_FIRSTTURNONLY,
	TECHEFFECT_SWITCHOUTUSER,
	TECHEFFECT_SWITCHOUTTARGET,
	TECHEFFECT_MAX
};

TechniqueStats gTechniqueStats[TECHNIQUE_MAX];

#endif // !__TECHNIQUE_H__
